# This yaml file can be used to setup other k8s control planes and worker nodes also.
- name: Kubernetes Node Setup
  hosts: localhost
  become: yes
  tasks:
    - name: Set SELinux in permissive mode
      command: setenforce 0

    - name: Configure SELinux to permissive
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=permissive'

    - name: Disable swap
      command: swapoff -a

    - name: Comment swap in fstab
      replace:
        path: /etc/fstab
        regexp: '^.*swap.*$'
        replace: '# &'

    - name: Install Podman
      dnf:
        name: podman
        state: present

    - name: Verify Podman installation
      command: podman --version

    - name: Load kernel modules
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Load overlay module
      modprobe:
        name: overlay

    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter

    - name: Apply sysctl params
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1

    - name: Apply sysctl settings
      command: sysctl --system

    - name: Verify kernel modules
      command: lsmod
      register: lsmod_output

    - name: Verify sysctl settings
      command: sysctl net.bridge.bridge-nf-call-iptables net.bridge.bridge-nf-call-ip6tables net.ipv4.ip_forward

    - name: Install Oracle Linux release package
      dnf:
        name: oraclelinux-release-el9
        state: present

    - name: Add proxy to dnf.conf
      lineinfile:
        path: /etc/dnf/dnf.conf
        line: 'proxy={{ proxy_url }}'

    - name: Add CRI-O repository
      copy:
        dest: /etc/yum.repos.d/cri-o.repo
        content: |
          [cri-o]
          name=CRI-O
          baseurl=https://download.opensuse.org/repositories/isv:/cri-o:/stable:/v1.32/rpm/
          enabled=1
          gpgcheck=1
          gpgkey=https://download.opensuse.org/repositories/isv:/cri-o:/stable:/v1.32/rpm/repodata/repomd.xml.key

    - name: Install CRI-O and dependencies
      dnf:
        name:
          - container-selinux
          - cri-o
        state: present
      register: cri_o_result

    - name: Enable and start CRI-O service
      systemd:
        name: crio
        enabled: yes
        state: started
      when: cri_o_result is succeeded

    - name: Create CRI-O proxy configuration directory
      file:
        path: /etc/systemd/system/crio.service.d/
        state: directory
      when: cri_o_result is succeeded

    - name: Create CRI-O proxy configuration
      copy:
        dest: /etc/systemd/system/crio.service.d/proxy.conf
        content: |
          [Service]
          Environment="HTTP_PROXY={{ proxy_url }}"
          Environment="HTTPS_PROXY={{ proxy_url }}"
          Environment="NO_PROXY={{ no_proxy }}"
      when: cri_o_result is succeeded

    - name: Reload systemd and restart CRI-O
      systemd:
        daemon_reload: yes
        name: crio
        state: restarted
      when: cri_o_result is succeeded

    - name: Add Kubernetes repository
      copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://pkgs.k8s.io/core:/stable:/v1.32/rpm/
          enabled=1
          gpgcheck=1
          gpgkey=https://pkgs.k8s.io/core:/stable:/v1.32/rpm/repodata/repomd.xml.key

    - name: Install Kubernetes packages
      dnf:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Enable and start kubelet service
      systemd:
        name: kubelet
        enabled: yes
        state: started

    - name: Verify Kubernetes installation
      command: kubeadm version

    - name: Verify kubectl installation
      command: kubectl version --client

    - name: Verify kubelet installation
      command: kubelet --version

    - name: Join command reminder
      command: echo "Use JOIN command now to join the k8s cluster"
